import { parseScene } from "@crowdsim/scene-schema";

export const bioCityDemoScene = parseScene({
  schemaVersion: "1.0.0",
  id: "biocity-rainy-high-street",
  name: "BioCity Rainy High Street",
  seed: 31,
  world: {
    width: 160,
    height: 96,
  },
  environmentFactors: [
    {
      id: "high-street-rain",
      name: "Rain over the high street",
      kind: "rain",
      severity: 0.8,
    },
  ],
  visualAssets: [
    {
      id: "rain-market-streetscape",
      name: "Rain Market Streetscape",
      kind: "gltf-scene",
      sourceUrl: "/assets/biocity/rain-market-streetscape.glb",
      lodSources: {
        high: "/assets/biocity/rain-market-streetscape.high.glb",
        low: "/assets/biocity/rain-market-streetscape.low.glb",
        medium: "/assets/biocity/rain-market-streetscape.glb",
      },
      originalSourceFormat: "sketchup",
      anchor: { x: 80, y: 48, z: 0 },
      calibration: {
        accuracyMeters: 0.5,
        simulationProxy: {
          entityId: "downtown-walkable",
          kind: "area",
        },
        unitScaleMeters: 1,
        upAxis: "y-up",
        verified: true,
      },
      rotationDegrees: 0,
      scale: 1,
      attribution: "SketchUp massing model converted to GLB for visual context",
    },
    {
      id: "bus-stop-shelter",
      name: "Bus Stop Shelter",
      kind: "gltf-prop",
      sourceUrl: "/assets/biocity/bus-stop-shelter.glb",
      lodSources: {
        low: "/assets/biocity/bus-stop-shelter.low.glb",
      },
      originalSourceFormat: "glb",
      anchor: { x: 122, y: 72, z: 0 },
      calibration: {
        accuracyMeters: 0.2,
        simulationProxy: {
          entityId: "rain-market-bus-stop",
          kind: "transitStop",
        },
        unitScaleMeters: 1,
        upAxis: "y-up",
        verified: true,
      },
      scale: 0.9,
    },
  ],
  areas: [
    {
      id: "downtown-walkable",
      geometry: {
        type: "polygon",
        points: [
          { x: 0, y: 0 },
          { x: 160, y: 0 },
          { x: 160, y: 96 },
          { x: 0, y: 96 },
        ],
      },
    },
  ],
  entrances: [
    {
      id: "west-arrivals",
      kind: "source",
      position: { x: 6, y: 52 },
      width: 8,
      arrivalRatePerMinute: 180,
    },
    {
      id: "metro-return",
      kind: "sink",
      position: { x: 150, y: 52 },
      width: 10,
    },
  ],
  roads: [
    {
      id: "rain-market-avenue",
      name: "Rain Market Avenue",
      geometry: {
        type: "polyline",
        points: [
          { x: 8, y: 54 },
          { x: 152, y: 54 },
        ],
      },
      widthMeters: 10,
      capacityPerMinute: 420,
    },
    {
      id: "bus-loop",
      name: "Bus Loop",
      geometry: {
        type: "polyline",
        points: [
          { x: 92, y: 72 },
          { x: 126, y: 72 },
          { x: 144, y: 58 },
        ],
      },
      widthMeters: 7,
      transitOnly: true,
    },
  ],
  buildings: [
    {
      id: "glass-arcade",
      name: "Glass Arcade",
      kind: "retail",
      footprint: {
        type: "polygon",
        points: [
          { x: 22, y: 16 },
          { x: 64, y: 16 },
          { x: 64, y: 40 },
          { x: 22, y: 40 },
        ],
      },
      entrancePosition: { x: 42, y: 40 },
      floors: 4,
      heightMeters: 18,
      visitorCapacity: 650,
      visual: {
        style: "glass-retail",
        signText: "Arcade",
      },
    },
    {
      id: "food-hall-south",
      name: "Food Hall South",
      kind: "mixedUse",
      footprint: {
        type: "polygon",
        points: [
          { x: 72, y: 18 },
          { x: 112, y: 18 },
          { x: 112, y: 42 },
          { x: 72, y: 42 },
        ],
      },
      entrancePosition: { x: 92, y: 42 },
      workerCapacity: 90,
      visitorCapacity: 520,
      visual: {
        style: "food-hall",
        signText: "Food Hall",
      },
    },
  ],
  transitStops: [
    {
      id: "rain-market-bus-stop",
      name: "Rain Market Bus Stop",
      roadId: "bus-loop",
      kind: "bus",
      position: { x: 122, y: 72 },
      capacity: 140,
      arrivalIntervalSeconds: 240,
      alightingPerArrival: 38,
      delayFactor: 1.25,
    },
  ],
  obstacles: [
    {
      id: "umbrella-queue-rails",
      name: "Umbrella Queue Rails",
      kind: "securityLine",
      geometry: {
        type: "polyline",
        points: [
          { x: 116, y: 64 },
          { x: 136, y: 64 },
        ],
      },
      routeCostMultiplier: 2.2,
    },
  ],
  hazards: [
    {
      id: "curbside-pooling",
      name: "Curbside Pooling",
      kind: "flood",
      position: { x: 98, y: 58 },
      radiusMeters: 9,
      affectedRoadId: "rain-market-avenue",
      startsAtSeconds: 900,
      endsAtSeconds: 3600,
      severity: 0.42,
      speedMultiplier: 0.76,
      routeCostMultiplier: 1.8,
      riskScore: 0.24,
    },
  ],
  weatherProfile: {
    id: "rainy-commute-profile",
    name: "Rainy Commute Profile",
    source: "manual",
    location: {
      name: "BioCity Downtown",
      latitude: 31.2304,
      longitude: 121.4737,
      timezone: "Asia/Shanghai",
    },
    samples: [
      {
        startsAtSeconds: 0,
        durationSeconds: 1800,
        condition: "rain",
        temperatureC: 21,
        apparentTemperatureC: 19,
        precipitationMmPerHour: 4.8,
        windSpeedMetersPerSecond: 5.2,
        windDirectionDegrees: 130,
        humidityPercent: 86,
        visibilityMeters: 4200,
      },
      {
        startsAtSeconds: 1800,
        durationSeconds: 2400,
        condition: "heavyRain",
        temperatureC: 20,
        apparentTemperatureC: 18,
        precipitationMmPerHour: 13.5,
        windSpeedMetersPerSecond: 8.4,
        windDirectionDegrees: 145,
        humidityPercent: 92,
        visibilityMeters: 1800,
      },
    ],
  },
  eventTimeline: {
    id: "rainy-ops-timeline",
    startsAtIso: "2026-06-16T00:00:00.000Z",
    events: [
      {
        id: "bus-delay-start",
        kind: "transitDelay",
        startsAtSeconds: 600,
        endsAtSeconds: 2400,
        targetId: "rain-market-bus-stop",
        payload: {
          delayFactor: 1.45,
        },
      },
      {
        id: "pooling-warning",
        kind: "hazardStart",
        startsAtSeconds: 900,
        targetId: "curbside-pooling",
      },
    ],
  },
  bioAgentProfiles: [
    {
      id: "commuter-rain-sensitive",
      name: "Rain-sensitive Commuter",
      kind: "commuter",
      spendingIntent: 0.18,
      weatherSensitivity: 0.86,
      riskTolerance: 0.32,
      shelterPreference: 0.78,
    },
    {
      id: "shopper-shelter-seeker",
      name: "Shelter-seeking Shopper",
      kind: "shopper",
      spendingIntent: 0.64,
      weatherSensitivity: 0.72,
      riskTolerance: 0.44,
      shelterPreference: 0.82,
    },
  ],
  shops: [
    {
      id: "brew-under-canopy",
      name: "Brew Under Canopy",
      position: { x: 36, y: 34 },
      entrancePosition: { x: 36, y: 40 },
      queueAnchor: { x: 38, y: 45 },
      size: { width: 12, height: 8 },
      attraction: 1.32,
      dwellMeanSeconds: 10,
      brand: {
        profileId: "brew-under-canopy",
        category: "coffee",
        visibility: 0.88,
        promotion: 0.18,
        personaAffinity: {
          commuter: 0.84,
          browser: 0.45,
        },
      },
    },
    {
      id: "raincoat-pop-up",
      name: "Raincoat Pop-up",
      position: { x: 86, y: 36 },
      entrancePosition: { x: 86, y: 42 },
      size: { width: 10, height: 7 },
      attraction: 1.48,
      dwellMeanSeconds: 8,
      brand: {
        profileId: "raincoat-pop-up",
        category: "service",
        novelty: 0.78,
        promotion: 0.35,
        personaAffinity: {
          commuter: 0.62,
          serviceSeeker: 0.9,
        },
      },
    },
    {
      id: "glass-arcade-store",
      name: "Glass Arcade Store",
      position: { x: 50, y: 30 },
      entrancePosition: { x: 50, y: 40 },
      queueAnchor: { x: 50, y: 44 },
      size: { width: 12, height: 8 },
      attraction: 1.1,
      dwellMeanSeconds: 9,
      capacity: 14,
    },
    {
      id: "food-hall-eatery",
      name: "Food Hall Eatery",
      position: { x: 100, y: 34 },
      entrancePosition: { x: 100, y: 44 },
      queueAnchor: { x: 100, y: 48 },
      size: { width: 14, height: 9 },
      attraction: 1.25,
      dwellMeanSeconds: 12,
      capacity: 16,
    },
    {
      id: "avenue-newsstand",
      name: "Avenue Newsstand",
      position: { x: 68, y: 49 },
      entrancePosition: { x: 68, y: 51 },
      queueAnchor: { x: 68, y: 53 },
      size: { width: 6, height: 4 },
      attraction: 0.85,
      dwellMeanSeconds: 5,
      capacity: 8,
    },
  ],
  visual: {
    defaultView: "isometric",
  },
});
