import { parseScene } from "@crowdsim/scene-schema";

export const demoScene = parseScene({
  schemaVersion: "1.0.0",
  id: "atrium-demo",
  name: "Atrium Demo",
  world: {
    width: 80,
    height: 48,
  },
  walls: [
    {
      id: "north-wall",
      geometry: {
        type: "polyline",
        points: [
          { x: 4, y: 4 },
          { x: 76, y: 4 },
        ],
      },
    },
  ],
  entrances: [
    {
      id: "main-entry",
      kind: "source",
      position: { x: 8, y: 44 },
      width: 4,
      arrivalRatePerMinute: 120,
    },
    {
      id: "east-exit",
      kind: "sink",
      position: { x: 76, y: 24 },
      width: 5,
    },
  ],
  areas: [
    {
      id: "walkable-floor",
      geometry: {
        type: "polygon",
        points: [
          { x: 0, y: 0 },
          { x: 80, y: 0 },
          { x: 80, y: 48 },
          { x: 0, y: 48 },
        ],
      },
    },
  ],
  targets: [
    {
      id: "info-desk",
      position: { x: 42, y: 20 },
    },
  ],
  shops: [
    {
      id: "coffee-pulse",
      name: "Coffee Pulse",
      position: { x: 18, y: 16 },
      size: { width: 8, height: 5 },
      attraction: 1.1,
      capacity: 18,
      dwellMeanSeconds: 540,
      brand: {
        profileId: "coffee-pulse",
        category: "coffee",
        brandPower: 0.74,
        priceTier: 2,
        novelty: 0.36,
        promotion: 0.22,
        visibility: 0.86,
        personaAffinity: { commuter: 0.9, browser: 0.52, family: 0.48 },
      },
    },
    {
      id: "mono-thread",
      name: "Mono Thread",
      position: { x: 32, y: 14 },
      size: { width: 10, height: 6 },
      attraction: 1.28,
      capacity: 32,
      dwellMeanSeconds: 780,
      brand: {
        profileId: "mono-thread",
        category: "fastFashion",
        brandPower: 0.68,
        priceTier: 3,
        novelty: 0.72,
        promotion: 0.42,
        visibility: 0.82,
        personaAffinity: { browser: 0.84, goalBuyer: 0.64, family: 0.5 },
      },
    },
    {
      id: "atelier-nine",
      name: "Atelier Nine",
      position: { x: 50, y: 13 },
      size: { width: 9, height: 6 },
      attraction: 1.85,
      capacity: 16,
      dwellMeanSeconds: 1120,
      brand: {
        profileId: "atelier-nine",
        category: "luxury",
        brandPower: 0.94,
        priceTier: 5,
        novelty: 0.45,
        promotion: 0.08,
        visibility: 0.72,
        personaAffinity: { luxuryBuyer: 0.96, goalBuyer: 0.68, browser: 0.34 },
      },
    },
    {
      id: "table-signal",
      name: "Table Signal",
      position: { x: 58, y: 30 },
      size: { width: 12, height: 7 },
      attraction: 1.42,
      capacity: 44,
      dwellMeanSeconds: 1680,
      brand: {
        profileId: "table-signal",
        category: "restaurant",
        brandPower: 0.78,
        priceTier: 3,
        novelty: 0.38,
        promotion: 0.18,
        visibility: 0.76,
        personaAffinity: { family: 0.86, browser: 0.56, commuter: 0.28 },
      },
    },
    {
      id: "little-orbit",
      name: "Little Orbit",
      position: { x: 28, y: 32 },
      size: { width: 10, height: 6 },
      attraction: 1.18,
      capacity: 26,
      dwellMeanSeconds: 900,
      brand: {
        profileId: "little-orbit",
        category: "family",
        brandPower: 0.64,
        priceTier: 3,
        novelty: 0.58,
        promotion: 0.24,
        visibility: 0.7,
        personaAffinity: { family: 0.92, browser: 0.45 },
      },
    },
    {
      id: "care-station",
      name: "Care Station",
      position: { x: 44, y: 32 },
      size: { width: 8, height: 5 },
      attraction: 1.06,
      capacity: 12,
      dwellMeanSeconds: 720,
      brand: {
        profileId: "care-station",
        category: "service",
        brandPower: 0.72,
        priceTier: 2,
        novelty: 0.2,
        promotion: 0.04,
        visibility: 0.66,
        personaAffinity: { serviceSeeker: 0.95, family: 0.42 },
      },
    },
  ],
});
